### ISSUE TITLE
Crash on location update

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookAndroid#110]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
	at com.myflightbook.android.ActMFBForm.SetUTCDateForField(ActMFBForm.java:242)
	at com.myflightbook.android.ActNewFlight.RefreshDetectedFields(ActNewFlight.java:1730)
	at Model.MFBFlightListener.TakeoffDetected(MFBFlightListener.java:86)
	at Model.MFBLocation.onLocationChanged(MFBLocation.java:330)
	at Model.MFBLocation$1.onReceive(MFBLocation.java:104)
	at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:308)
	at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
	at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:118)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object referenceAttempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference

**Comment by ericberman** [comment]
Can't repro
