### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookAndroid#121]
Version 3.4.2018.09.11 (84)

(unknown user)       

java.lang.NoClassDefFoundError: java.util.Objects
	at com.myflightbook.android.ActMFBForm.onCreate(ActMFBForm.java:203)
	at android.support.v4.app.Fragment.performCreate(Fragment.java:2331)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1386)
	at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1188)
	at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1071)
	at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:115)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2380)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:784)
	at com.myflightbook.android.MFBMain.onTabChanged(MFBMain.java:640)
	at com.myflightbook.android.MFBMain.onCreate(MFBMain.java:383)
	at android.app.Activity.performCreate(Activity.java:5133)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
	at android.app.ActivityThread.access$600(ActivityThread.java:141)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5103)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(Native Method) java.util.Objectsjava.util.Objects

**Comment by ericberman** [comment]
static methods in java.util.objects like requireNonNull were added in SDK 19, which is my minimum.  So this should have worked.
