### ISSUE TITLE
Warning about use in flight pops up and disappears?

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookAndroid#252]

**Comment by ericberman** [comment]
2021-12-19 10:15:10.478 9277-9277/com.myflightbook.android E/WindowManager: android.view.WindowLeaked: Activity com.myflightbook.android.MFBMain has leaked window DecorView@c2ae8ab[MFBMain] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:783)
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:767)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:389)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:133)
        at android.app.Dialog.show(Dialog.java:345)
        at Model.MFBUtil.Alert(MFBUtil.java:55)
        at com.myflightbook.android.MFBMain.onCreate(MFBMain.java:446)
        at android.app.Activity.performCreate(Activity.java:8051)
        at android.app.Activity.performCreate(Activity.java:8031)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by ericberman** [comment]
Just put the warning in the sign-in dialog instead
