### ISSUE TITLE
Null pointer in hobbs changed

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookAndroid#271]
Version 2022.04.27.1 (144)

java.lang.NullPointerException
	at com.myflightbook.android.ActMFBForm.doubleFromField(ActMFBForm.kt:357)
	at com.myflightbook.android.ActNewFlight.onHobbsChanged(ActNewFlight.kt:1004)
	at com.myflightbook.android.ActNewFlight.onViewCreated$lambda-15(ActNewFlight.kt:458)
	at com.myflightbook.android.ActNewFlight.$r8$lambda$DdZ5hRDWVuPLNmXgeKPUQuro7rQ(Unknown Source:0)
	at com.myflightbook.android.ActNewFlight$$ExternalSyntheticLambda10.onFocusChange(Unknown Source:2)
	at android.view.View.onFocusChanged(View.java:8460)
	at android.widget.TextView.onFocusChanged(TextView.java:12202)
	at android.widget.EditText.onFocusChanged(EditText.java:242)
	at android.view.View.clearFocusInternal(View.java:8297)
	at android.view.View.unFocus(View.java:8330)
	at android.view.ViewGroup.unFocus(ViewGroup.java:1223)
	at android.view.ViewGroup.unFocus(ViewGroup.java:1223)
	at android.view.ViewGroup.unFocus(ViewGroup.java:1223)
	at android.view.ViewGroup.unFocus(ViewGroup.java:1223)
	at android.view.ViewGroup.unFocus(ViewGroup.java:1223)
	at android.view.ViewGroup.unFocus(ViewGroup.java:1223)
	at android.view.ViewGroup.unFocus(ViewGroup.java:1223)
	at android.view.ViewGroup.unFocus(ViewGroup.java:1223)
	at android.view.ViewGroup.unFocus(ViewGroup.java:1223)
	at android.view.ViewGroup.unFocus(ViewGroup.java:1223)
	at android.view.ViewGroup.unFocus(ViewGroup.java:1223)
	at android.view.ViewGroup.unFocus(ViewGroup.java:1223)
	at android.view.ViewGroup.unFocus(ViewGroup.java:1223)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:6397)
	at android.view.ViewGroup.removeViewAt(ViewGroup.java:6360)
	at com.android.internal.policy.DecorView.clearContentView(DecorView.java:3783)
	at com.android.internal.policy.PhoneWindow.clearContentView(PhoneWindow.java:594)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6012)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6318)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6212)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:65)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:6301)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2448)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
nullnull

**Comment by ericberman** [comment]
can't repro, haven't seen happen again
