### ISSUE TITLE
Null pointer in ActNewFlight

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookAndroid#272]
Version 2022.04.27.1 (144)

java.lang.NullPointerException
	at com.myflightbook.android.ActNewFlight.onClick(ActNewFlight.kt:932)
	at android.view.View.performClick(View.java:7455)
	at android.view.View.performClickInternal(View.java:7432)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28810)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
nullnull

**Comment by ericberman** [comment]
can't repro
