### ISSUE TITLE
Crash in saveCurrentFlightID

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookAndroid#31]
When is getActivity() not getActivity()?  Apparently if the activity has not yet been attached. Android is so fucked up sometimes...

3.0.1 (63)

java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.app.Activity.getPreferences(int)' on a null object reference
	at Model.MFBFlightListener.saveCurrentFlightId(Unknown Source)
	at com.myflightbook.android.ActNewFlight.saveCurrentFlight(Unknown Source)
	at com.myflightbook.android.ActNewFlight.SetLogbookEntry(Unknown Source)
	at com.myflightbook.android.ActNewFlight.ResetFlight(Unknown Source)
	at com.myflightbook.android.ActNewFlight.invalidate(Unknown Source)
	at com.myflightbook.android.MFBMain.invalidateAll(Unknown Source)
	at com.myflightbook.android.DlgSignIn$SoapTask.onPostExecute(Unknown Source)
	at com.myflightbook.android.DlgSignIn$SoapTask.onPostExecute(Unknown Source)
	at android.os.AsyncTask.finish(AsyncTask.java:651)
	at android.os.AsyncTask.access$500(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Attempt to invoke virtual method 'android.content.SharedPreferences android.app.Activity.getPreferences(int)' on a null object referenceAttempt to invoke virtual method 'android.content.SharedPreferences android.app.Activity.getPreferences(int)' on a null object reference

**Comment by ericberman** [comment]
Simply do a null check, since getActivity() can (yikes) actually return null periodically; if that's the case, the activity isn't attached and there isn't much we can do.  Fixed in version 64.
