### ISSUE TITLE
NullPointer Crash in WebServices Invoke

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookAndroid#32]
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException
	at com.myflightbook.android.WebServices.MFBSoap.Invoke(Unknown Source)
	at com.myflightbook.android.WebServices.RecentFlightsSvc.RecentFlightsWithQueryAndOffset(Unknown Source)
	at com.myflightbook.android.ActRecentsWS$RefreshFlightsTask.doInBackground(Unknown Source)
	at com.myflightbook.android.ActRecentsWS$RefreshFlightsTask.doInBackground(Unknown Source)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

**Comment by ericberman** [comment]
looks like getContext() can return null; using ActRecentsWS.this.getContext() instead, hopefully that fixes it.  Will be live in 64.

**Comment by ericberman** [comment]
Version 3.0.2 (64)

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:318)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)
Caused by: java.lang.NullPointerException: null Context passed to Invoke
	at com.myflightbook.android.WebServices.MFBSoap.Invoke(Unknown Source)
	at com.myflightbook.android.WebServices.FlightPropertiesSvc.PropertiesForFlight(Unknown Source)
	at com.myflightbook.android.ActNewFlight$UpdateAndViewPropsTask.doInBackground(Unknown Source)
	at com.myflightbook.android.ActNewFlight$UpdateAndViewPropsTask.doInBackground(Unknown Source)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
An error occurred while executing doInBackground()An error occurred while executing doInBackground()

**Comment by ericberman** [comment]
Tried setting the context synchronously, fail over to application context, further fail gracefully if it's null.
