### ISSUE TITLE
Crash - null logbook entry

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookAndroid#33]
Version 3.0.1 (63)

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Boolean Model.LogbookEntry.IsNewFlight()' on a null object reference
	at com.myflightbook.android.ActNewFlight.SubmitFlight(Unknown Source)
	at com.myflightbook.android.ActNewFlight.onOptionsItemSelected(Unknown Source)
	at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2199)
	at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2284)
	at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:353)
	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:427)
	at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1244)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:801)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:155)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:954)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:944)
	at android.widget.ActionMenuView.invokeItem(ActionMenuView.java:658)
	at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:256)
	at android.view.View.performClick(View.java:5698)
	at android.widget.TextView.performClick(TextView.java:10888)
	at android.view.View$PerformClick.run(View.java:22570)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7231)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Attempt to invoke virtual method 'java.lang.Boolean Model.LogbookEntry.IsNewFlight()' on a null object referenceAttempt to invoke virtual method 'java.lang.Boolean Model.LogbookEntry.IsNewFlight()' on a null object reference

**Comment by ericberman** [comment]
Put in an if (m_le == null) guard on this.  Not sure why it would ever happen, though...
