### ISSUE TITLE
crash in cannot perform action after onSaveInstanceStat

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookAndroid#35]
Version 3.0.1 (63)

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1527)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1545)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:654)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:621)
	at com.myflightbook.android.MFBMain.onTabChanged(Unknown Source)
	at android.widget.TabHost.invokeOnTabChangeListener(TabHost.java:421)
	at android.widget.TabHost.setCurrentTab(TabHost.java:406)
	at android.widget.TabHost.setCurrentTabByTag(TabHost.java:269)
	at com.myflightbook.android.MFBMain$RefreshTask.onPostExecute(Unknown Source)
	at com.myflightbook.android.MFBMain$RefreshTask.onPostExecute(Unknown Source)
	at android.os.AsyncTask.finish(AsyncTask.java:660)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
Can not perform this action after onSaveInstanceStateCan not perform this action after onSaveInstanceState

**Comment by ericberman** [comment]
I think we can ignore this - if SaveInstanceState has been called, we're already shutting down.  this is a race condition.
