### ISSUE TITLE
crash - null logbook entry

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookAndroid#37]
Version 3.0.1 (63)

java.lang.NullPointerException: Attempt to read from field 'int Model.LogbookEntry.idFlight' on a null object reference
	at com.myflightbook.android.ActNewFlight.onOptionsItemSelected(Unknown Source)
	at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2199)
	at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2284)
	at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:353)
	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:427)
	at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1215)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
	at android.widget.ActionMenuView.invokeItem(ActionMenuView.java:616)
	at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:152)
	at android.view.View.performClick(View.java:5637)
	at android.view.View$PerformClick.run(View.java:22429)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Attempt to read from field 'int Model.LogbookEntry.idFlight' on a null object referenceAttempt to read from field 'int Model.LogbookEntry.idFlight' on a null object reference

**Comment by ericberman** [comment]
Dupe of #33
