### ISSUE TITLE
Crash in getLayoutInflator

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookAndroid#38]
Version 3.0.1 (63)

java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.LayoutInflater android.support.v4.app.FragmentActivity.getLayoutInflater()' on a null object reference
	at com.myflightbook.android.ActMFBForm.setUpImageGallery(Unknown Source)
	at com.myflightbook.android.ActNewFlight.setUpGalleryForFlight(Unknown Source)
	at com.myflightbook.android.ActNewFlight.refreshGallery(Unknown Source)
	at com.myflightbook.android.ActMFBForm$AddCameraTask.onPostExecute(Unknown Source)
	at com.myflightbook.android.ActMFBForm$AddCameraTask.onPostExecute(Unknown Source)
	at android.os.AsyncTask.finish(AsyncTask.java:651)
	at android.os.AsyncTask.access$500(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7225)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Attempt to invoke virtual method 'android.view.LayoutInflater android.support.v4.app.FragmentActivity.getLayoutInflater()' on a null object referenceAttempt to invoke virtual method 'android.view.LayoutInflater android.support.v4.app.FragmentActivity.getLayoutInflater()' on a null object reference

**Comment by ericberman** [comment]
Appears to be line 282: LayoutInflater l = getActivity().getLayoutInflater();
so getActivity() is returning null.  Can happen if activity is not yet attached, so I'll just check for that for now.
