### ISSUE TITLE
Crash: null logbookentry

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookAndroid#39]
Version 3.0.1 (63)

java.lang.NullPointerException: Attempt to read from field 'int Model.LogbookEntry.cNightLandings' on a null object reference
	at Model.MFBFlightListener.FSLandingDetected(Unknown Source)
	at Model.MFBLocation.onLocationChanged(Unknown Source)
	at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:297)
	at android.location.LocationManager$ListenerTransport.-wrap0(LocationManager.java)
	at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:242)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6688)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Attempt to read from field 'int Model.LogbookEntry.cNightLandings' on a null object referenceAttempt to read from field 'int Model.LogbookEntry.cNightLandings' on a null object reference

**Comment by ericberman** [comment]
Put in a guard (m_leNewFlight == null) here a la AddNightTime
