### ISSUE TITLE
Crash in acttotals, currency

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookAndroid#82]
[This](https://stackoverflow.com/questions/10919240/fragment-myfragment-not-attached-to-activity) might have some useful info - may just need to test and exit if null
java.lang.NullPointerException: getView returned null in BindTable in ActTotals
	at com.myflightbook.android.ActTotals.BindTable(ActTotals.java:220)
	at com.myflightbook.android.ActTotals.access$200(ActTotals.java:55)
	at com.myflightbook.android.ActTotals$RefreshTotals.onPostExecute(ActTotals.java:108)
	at com.myflightbook.android.ActTotals$RefreshTotals.onPostExecute(ActTotals.java:65)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6753)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
getView returned null in BindTable in ActTotalsgetView returned null in BindTable in ActTotals

**Comment by ericberman** [comment]
Here is the currency one:

java.lang.NullPointerException: tl is null in BindTable (ActCurrency)!
        at com.myflightbook.android.ActCurrency.BindTable(ActCurrency.java:132)
        at com.myflightbook.android.ActCurrency.access$100(ActCurrency.java:52)
        at com.myflightbook.android.ActCurrency$RefreshCurrency.onPostExecute(ActCurrency.java:100)
        at com.myflightbook.android.ActCurrency$RefreshCurrency.onPostExecute(ActCurrency.java:61)
        at android.os.AsyncTask.finish(AsyncTask.java:667)
        at android.os.AsyncTask.-wrap1(AsyncTask.java)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6823)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1557)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
tl is null in BindTable (ActCurrency)!tl is null in BindTable (ActCurrency)!
