### ISSUE TITLE
another get theme crash

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookAndroid#85]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference
	at android.app.AlertDialog.resolveDialogTheme(AlertDialog.java:224)
	at android.app.AlertDialog$Builder.<init>(AlertDialog.java:459)
	at Model.MFBUtil.Alert(MFBUtil.java:48)
	at Model.MFBUtil.Alert(MFBUtil.java:57)
	at com.myflightbook.android.ActRecentsWS$RefreshFlightsTask.onPostExecute(ActRecentsWS.java:356)
	at com.myflightbook.android.ActRecentsWS$RefreshFlightsTask.onPostExecute(ActRecentsWS.java:304)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object referenceAttempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference

**Comment by ericberman** [comment]
Dupe of #84
